# Site settings
title: A Man and His Code
header-img: img/home-bg.png
email: hector_ariceaga@hotmail.com
copyright_name: Hector-Ariceaga
description: > # this means to ignore newlines until "baseurl:"
  Chronicling a Journey of Study, Work, and Growth
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Hector-Ariceaga
learn_profile: Hector-Ariceaga
email_username: hector_ariceaga@hotmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
